version: '3'
services:
  web:
    build:
      context: .
      args:
        - APP_SETTINGS=app.config.TestingConfig
    command: bash -c "py.test"
    environment:
      - APP_SETTINGS=app.config.TestingConfig
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=pam_challenge_test